CREATE TABLE T_COMMON_SYSTEM_CONFIG (
  ID NUMBER(18,0),
  KEY VARCHAR2(50),
  VALUE VARCHAR2(200),
  REMARK VARCHAR2(50),
  CREATE_BY VARCHAR2(50),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_BY VARCHAR2(50),
  UPDATE_TIME TIMESTAMP(6)
);
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.ID IS '主键';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.KEY IS '键';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.VALUE IS '值';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.REMARK IS '备注';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.UPDATE_BY IS '修改人';
COMMENT ON COLUMN T_COMMON_SYSTEM_CONFIG.UPDATE_TIME IS '修改时间';
COMMENT ON TABLE T_COMMON_SYSTEM_CONFIG IS '系统配置表';

CREATE SEQUENCE SEQ_T_COMMON_SYSTEM_CONFIG
MINVALUE 1000
MAXVALUE 999999999999999999
START WITH 1000
INCREMENT BY 1
CACHE 1000;

CREATE UNIQUE INDEX IX_T_COMMON_SYSTEM_CONFIG_ID ON T_COMMON_SYSTEM_CONFIG(ID) ONLINE;
ALTER TABLE T_COMMON_SYSTEM_CONFIG ADD CONSTRAINT PK_T_COMMON_SYSTEM_CONFIG PRIMARY KEY(ID) USING INDEX IX_T_COMMON_SYSTEM_CONFIG_ID;
CREATE INDEX IX_T_COMMON_SYSTEM_CONFIG_K ON T_COMMON_SYSTEM_CONFIG(KEY) ONLINE;