spring:
    datasource:
        url: jdbc:sqlserver://150.158.159.17:1433;databaseName=Hulk
        username: sa
        password: TrGAF7tn9L
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            pool-name: Optimus_HikariCP         # 连接池名称
            minimum-idle: 10                    # 最小空闲连接数
            maximum-pool-size: 15               # 连接池最大连接数
            connection-timeout: 30000           # 数据库连接超时时间
            idle-timeout: 60000                 # 空闲链接存活最大时间
            max-lifetime: 600000                # 连接池中链接的最长生命周期 
            auto-commit: true                   # 连接池中链接的自动提交行为

    cache:
        type: caffeine
        cache-names:
            - systemConfig
            - systemMemberIdConfig
            - memberChainConfig
        caffeine:
            spec: maximumSize=1000, expireAfterWrite=600s

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        defaultPropertyInclusion: NON_EMPTY
        deserialization:
            fail-on-unknown-properties: false
        serialization:
            fail-on-empty-beans: false
        parser:
            allow-unquoted-control-chars: true

mybatis:
    mapper-locations: classpath*:/mappers/**/*.xml
    type-aliases-package: com.optimus.dao.domain
    configuration:
        map-underscore-to-camel-case: true

logging:
    file:
        path: /Users/admin/Appspace/optimus/logs
    config: classpath:logback-spring.xml